### ISSUE TITLE
Performance hit for features w/ large number of user ids

### ISSUE THREAD

**Issue by burin** [fetlife/rollout#103]
### Background

I noticed that my requests were slow when looking up whether a user should see a feature, especially as I introduced more features with more user ids. I was interested in improving the `.active?(feature, id)` performance, which is why I ran into this.

### What I found

When working with a feature with a large number of user ids, feature retrieval takes a while (`130ms` for a feature with `100k` user ids).

I narrowed it down to the `.to_set` call when creating the feature:

https://github.com/fetlife/rollout/blob/master/lib/rollout.rb#L18

Using the set improves lookup performance, but costs a lot up front. The benchmarks in [this PR](https://github.com/fetlife/rollout/pull/83) didn't take into account the cost to create the set.

During a response/request cycle, it's likely that we create the feature once, and do a couple operations on it (e.g. `.active?`), so optimizing the lookup performance might not be appropriate.

### Recommendation

My recommendation would be to make using sets optional. There may be some cases where you have a long living instance of a `Feature` and want to do many lookups, but for the most part, I think using an array is an OK compromise.

### Benchmarks

Here's a benchmark that simulates the creation of the list of users from a raw string of comma-delimited user ids and checks whether a user id is in the list (set vs array vs string).

```
# create a set of raw_users in a string
raw_users = []
100_000.times {|num| raw_users << num }
raw_users = raw_users.join(',')

iterations = 100

# benchmark the way that rollout does an `active?` check w/ a set
## 10.880000   0.180000  11.060000 ( 11.090479) -> each operation takes about 110ms

Benchmark.bm do |bm|
  # joining an array of strings
  bm.report do
    iterations.times do |i|
      users = (raw_users || "").split(",").map(&:to_s).to_set
      users.include?(i)
    end
  end
end

# benchmark checking for a value in an array
## 2.430000   0.080000   2.510000 (  2.520499) -> each operation takes about 25ms

Benchmark.bm do |bm|
  # joining an array of strings
  bm.report do
    iterations.times do |i|
      users = (raw_users || "").split(",")
      users.include?(i)
    end
  end
end

# benchmark checking for a value in the string
## 0.000000   0.000000   0.000000 (  0.005260) -> each operation takes about .05ms

Benchmark.bm do |bm|
  # joining an array of strings
  bm.report do
    iterations.times do |i|
      users = (raw_users || "")
      !!users.match(/^#{i},|,#{i},|,#{i}$/)
    end
  end
end


```

**Comment by reneklacan** [comment]
@burin Amazing! Thank you really for for an effort ... PR to fix this would be welcome! If you don't have time then no worries, I will eventually get to it!
