### ISSUE TITLE
Test with redis-rb 4.0.0 RC1

### ISSUE THREAD

**Issue by djanowski** [fetlife/rollout#107]
I just released redis-rb 4.0.0 RC1.

Can you please test against it and report back?

Thank you!

**Comment by reneklacan** [comment]
@djanowski Sure, we would love to! 👍

**Comment by reneklacan** [comment]
@djanowski I've made sure we are testing on redis-rb 4.0.0 RC1 as well (https://github.com/fetlife/rollout/issues/108) ... everything looks fine!

I am also going to try 4.0.0 RC1 with our rails monolith's specs where we extensively using Redis and I will let if I discover any problems!

**Comment by reneklacan** [comment]
@djanowski I see some incompatibility with https://github.com/resque/redis-namespace due fact they use `redis (>= 3.0.4, ~> 3.0)` version constraint

**Comment by reneklacan** [comment]
@djanowski I see you already opened issue in their repo, never mind :D

**Comment by djanowski** [comment]
See [this discussion](https://github.com/mperham/sidekiq/issues/3256) about redis-namespace. Thanks.
