### ISSUE TITLE
User Primary Key is UUID: How will this work with percentage rollouts?

### ISSUE THREAD

**Issue by danielschwartz** [fetlife/rollout#109]
Hi,

The User Percentages rollout section, defines the algorithm as using CRC32, which seem to expect only integers to determine percentage rollouts. How will this feature interact with the knowledge that our User's primary key is not an auto incrementing integer, but a UUID generated by Postgres using `uuid_generate_v4()`. Should I just avoid this feature altogether? Will having UUID's as my user's primary key break anything else in this gem?

**Comment by reneklacan** [comment]
@danielschwartz I am not sure to be honest but it's very valid question. I am going to investigate this and make sure gem works with UUID. Thank you!

**Comment by danielschwartz** [comment]
@reneklacan awesome, appreciate it! I've done a random test by doing ` User.all.to_a.select{|u| Zlib.crc32(u.id.to_s) % 100 < 50 }.count` and number of users on the other seems somewhat correct (it's off by a couple, but not enough to actually matter). As long as the rest of the gem doesnt care if the ID is a string, I don't *think* it should be a problem

**Comment by danielschwartz** [comment]
@reneklacan i've been running rollout in production where my users table PK is a uuid_v4() and it's been working perfectly. Just figured i'd update this issue so anyone else how comes across it will know that uuid's do in fact work.
