### ISSUE TITLE
In case the rollout is not exist - return nil.

### ISSUE THREAD

**Issue by yossi-eynav** [fetlife/rollout#111]
The method `get` should return nil in case rollout is no exist.
This way the behaviour of the method  is more predictable.

What do you think?

**Comment by p-salido** [comment]
@yossi-eynav `rollout.get` of an undefined feature already returns nil, what do you mean by "rollout is no exist"?

**Comment by yossi-eynav** [comment]
![image](https://user-images.githubusercontent.com/8016250/27087127-ceeee6e8-505c-11e7-84cf-a4418abeacc0.png)

**Comment by p-salido** [comment]
You are correct there, my apologies.

**Comment by reneklacan** [comment]
Returning `nil` would be a breaking change so I'd like to avoid that if possible. But if it's very important to you I'd accept PR adding method like `exists?` to the `Rollout::Feature` class or similar meaningful implementation not breaking backward compatibility.

**Comment by yossi-eynav** [comment]
https://github.com/fetlife/rollout/pull/122
