### ISSUE TITLE
Announcement - A new user interface dashboard for rollout gem 

### ISSUE THREAD

**Issue by yossi-eynav** [fetlife/rollout#113]
Hi all,
I just wanted to inform all the people that care about rollout gem that we @ Fiverr built a new client app for managing our rollouts. 
https://github.com/fiverr/rollout_dashboard/

![](https://cloud.githubusercontent.com/assets/8016250/22857588/4fc5a084-f0b0-11e6-99fb-4beda0ab44d5.png)

**Comment by reneklacan** [comment]
@yossi-eynav This looks awesome. I look forward to try it out. Maybe we should also add it to README for better discovery! What do you think?

**Comment by yossi-eynav** [comment]
It would be AWESOME!
I'll send a PR shortly.

**Comment by reneklacan** [comment]
@yossi-eynav https://github.com/fetlife/rollout/commit/9eca5f1c395329d3b4f208a15b2ad9d851f231ba

**Comment by yossi-eynav** [comment]
@reneklacan Great!
I would appreciate if you could leave your suggestions / comments / ideas that you have regards `Rollout-Dashboard` and `Rollout-Service`

**Comment by reneklacan** [comment]
@yossi-eynav I haven't tried it yet but from scan through README of both projects my first thought was that both projects should be gems as well and there should be one gem integrating both of them which would allow you to mount dashboard as rack endpoint which would allow you setup dashboard in basically with just adding one line to your app. (something like sidekiq's dashboard https://github.com/mperham/sidekiq/wiki/Monitoring -> you can just do `mount Sidekiq::Web => '/sidekiq'` and everything works)

**Comment by yossi-eynav** [comment]
@reneklacan 
on which app do you wanna mount it? production app? backoffice app?
I don't believe it's a good practice to host your backoffice logic inside your production app - (separation of concern)

As I see it, the rollout-service is a stand alone service and not a 3rd party vendor (therefor it's not a gem).

**Comment by ecielam** [comment]
This should absolutely be something I can add to an existing app,  just like Resque/Sidekiq admin consoles.  The fact that I can't means I won't use it, since I don't want to have to deal with adding 'Yet Another Service' to my deployment process, when everything else can integrate into the same service.

Additionally, since it's built on Node, that's "yet another dependency" to add.  I'm surprised about this choice since your API already depends on Ruby.  At minimum, this should be another Rack application.

Looks great, but unusable for me due to the above.

**Comment by yossi-eynav** [comment]
@ecielam 
Hi man, thanks for your review!
About node - the node it just serving the static files, if you don't want to set it as a service you can simply upload the dist files to s3. no need to run node.

You can mount the service as a Rack application in your existing service, no need for an extra dependency. 

let me know your thoughts

**Comment by Bertg** [comment]
Suggest to close this issue.
