### ISSUE TITLE
Missing release tags

### ISSUE THREAD

**Issue by p-salido** [fetlife/rollout#117]
I am looking at updating rollout dependency in our project. We are at 2.3.0. There is no 2.3.0 tag in this repo hence getting a diff between 2.3.0 and 2.4.1 is not possible. 2.4.1 tag also does not exist.

https://rubygems.org/gems/rollout/versions/2.1.0

**Comment by reneklacan** [comment]
@p-salido Sorry, my bad, I forgot... Fixed! Created both 2.3.0 and 2.4.1
