### ISSUE TITLE
Modulus operator does not create uniformly distributed random numbers

### ISSUE THREAD

**Issue by p-salido** [fetlife/rollout#118]
https://github.com/fetlife/rollout/blob/master/lib/rollout.rb#L91

https://stackoverflow.com/questions/10984974/why-do-people-say-there-is-modulo-bias-when-using-a-random-number-generator#10984975

**Comment by reneklacan** [comment]
There's already similar issue https://github.com/fetlife/rollout/issues/58

We know it's not perfect, do you have suggestion how to address this? :)
