### ISSUE TITLE
Missing dependency on json

### ISSUE THREAD

**Issue by p-salido** [fetlife/rollout#121]
It is my understanding that json is not part of ruby standard library, hence needs to be declared as a dependency of rollout as of https://github.com/fetlife/rollout/commit/7b7bfc56a770a69749ea59edaa2072f9cefb502c.

**Comment by reneklacan** [comment]
`json` is part of the standard library

http://ruby-doc.org/stdlib-2.0.0/

**Comment by p-salido** [comment]
My bad, I made an effort to check that.
