### ISSUE TITLE
Google Calendar and iCalendar Integration

### ISSUE THREAD

**Issue by GitSnake** [fetlife/rollout#127]
The main website has email notifications and a calendar sprite but what I feel should be the next step with events should be the calendar integration so you don't have to go to the site and check or manually input the event into a separate calendar.

Thoughts?

**Comment by Bertg** [comment]
@GitSnake I think this Issue is not meant for this project. AM I correct? Please close if so.

**Comment by GitSnake** [comment]
@Bertg It was originally meant for this project. I will certainly close the issue if people don't agree, but what is the harm in simply putting a checkbox if someone wants the information loaded into a calendar? Giving the option to activate that feature doesn't seem harmful to privacy. Perhaps I'm wrong though. Please advise.
