### ISSUE TITLE
Activate and Deactive methods work. But activate_user and deactivate_user do not.

### ISSUE THREAD

**Issue by eddbrown** [fetlife/rollout#132]
![screen shot 2018-02-05 at 16 10 04](https://user-images.githubusercontent.com/10394150/35814873-13956cf8-0a8f-11e8-838e-f7d4aa48010e.png)

The deactivate and activate methods work well. The deactivate_user method does not, as shown above!

**Comment by ErebusBat** [comment]
This is expected (and also a duplicate report).  @reneklacan explained the problem well in the original report https://github.com/fetlife/rollout/issues/87#issuecomment-237365901
