### ISSUE TITLE
Persistent connections and Unicorn preload_app

### ISSUE THREAD

**Issue by kcm** [FetLife/rollout#30]
Rollout seems to get confused when restarting a unicorn setup, because it's using the old Redis connections.

```
ActionView::Template::Error (Tried to use a connection from a child process without reconnecting. You need to reconnect to Redis after forking.):
```

Is there any workaround currently? The way I see it, there's no straightforward way to just reinitialize an existing Rollout with a new Redis object, and I'd rather not put the entire Rollout initializer in the unicorn ```after_fork``` block.

**Comment by jlecour** [comment]
this seems kind of related to https://github.com/FetLife/rollout/issues/66

**Comment by reneklacan** [comment]
This has been resolved in Redis gem https://github.com/redis/redis-rb/pull/414
