### ISSUE TITLE
Rollouts aren't evenly distributed

### ISSUE THREAD

**Issue by EricR** [fetlife/rollout#58]
The algorithm implemented in `user_in_percentage?` is flawed, because it doesn't distribute evenly.

```
(1..1_000).select {|x| Zlib.crc32(x.to_s) % 100 < 25 }.count # => 271. Expected value would be 250
```

As a side note, CRC32 is prone to hash collisions (see [here](http://preshing.com/20110504/hash-collision-probabilities/)).

**Comment by p-salido** [comment]
Doing a `<` or `>` vs an appropriate boundary in the 32 bit integer space should be an improvement over the current situation:

- it would address the auto increment increment
- while it would not provide 100% uniformness given the 32 bit space I'd say it's as close as is practical
- still a single operation

Unless I'm missing something.

**Comment by reneklacan** [comment]
Let's close this issue as https://github.com/fetlife/rollout/pull/120 improved this a bit and relative error is small enough.
