### ISSUE TITLE
Generic Model-centric Rollouts

### ISSUE THREAD

**Issue by AlexRiedler** [FetLife/rollout#75]
Just throwing this idea out there, and if it would be supported by this gem:
Instead of per-user rollouts; per-model rollouts as well.

Some application might have features that if rolled out, should only be rolled out to anything interacting with a particular model.

e.g. All new repositories should have this feature enabled; but all old repositories shouldn't

Would it make sense to roll this into this gem? I am willing to spend the time doing it, just want to get some input first! (e.g. what type of interface, etc).

It might actually might make sense to drop groups or a new data format for this feature as well; cause groups could be a Value type model (that is used in the namespace); and `.active?('feature', RolloutGroup('foo')).`

Thoughts? Input? Discussion?

**Comment by AlexRiedler** [comment]
I should have also noted that I understand there is ways around this currently:
create a namespaced back redis storage engine and rollout for each type, and add_user takes a Repository object instead of a user.

**Comment by eric** [comment]
Your suggestion is what I currently do. We have both User and Company rollout instances.

**Comment by reneklacan** [comment]
Namespaced redis sounds like the most reasonable approach to this problem without adding to much of a complexity to the rollout gem.
