### ISSUE TITLE
Allow a check to see if any rollouts are active?

### ISSUE THREAD

**Issue by andy4thehuynh** [fetlife/rollout#96]
I needed to check if there were any rollouts active for a specific user. Could be a useful feature.

**Comment by reneklacan** [comment]
@andy4thehuynh I think it has been implemented by https://github.com/FetLife/rollout/pull/90 ... can you please try it? :)

**Comment by reneklacan** [comment]
closing for now... feel free to reopen :)

**Comment by andy4thehuynh** [comment]
Go for it! Our app is using an older version of Rollout that doesn't have the new features.
