### ISSUE TITLE
Feature Request: System Group/Accounts

### ISSUE THREAD

**Issue by rdejuana** [fetlife/rollout#97]
Have y'all thought about adding account support?

Our system has the concept of accounts which are collections of users.  We would like to enable a feature for a account without having to add each individual user.

**Comment by eric** [comment]
We do it by using another Rollout instance for the account IDs. There's no need for additional features.

**Comment by rdejuana** [comment]
How are you doing that?  We talked about that solution here, but it looks like you are using the same redis name spacing and would potentially have conflicts.

**Comment by eric** [comment]
You can use [Redis Namespaces](https://github.com/fetlife/rollout#namespacing) as referenced in the README.

**Comment by rdejuana** [comment]
ah, thanks!

**Comment by Bertg** [comment]
Alternatively... instead of passing the objects to rollout (ex: ```$rollout.active?(:feature, user)```) you can pass in the id yourself. This way you can manipulate that the ids for users and accounts are different.

```ruby
$rollout.active?(:feature, user.id)
$rollout.active?(:feature, "a:#{user.account.id}")
```

Also, i think we can close this ticket. No?
